Repository strangelove-ventures/interchaintest, pull requests merged in 2023-09, with the labels that each got.

#735 Readme + Mergify updates for SDK 50 Support
  .github/mergify.yml
  README.md
  docs/buildBinary.md
Labels: BACKPORT

#746 `[BP: v7 <- #737]` local-ic: CI + fix build
  .github/workflows/local-interchain.yaml
  local-interchain/go.mod
  local-interchain/go.sum
  local-interchain/interchain/genesis.go
Labels: backported

#740 Cleaner ExportState via document for SDK v47+
  chain/cosmos/chain_node.go
  examples/cosmos/chain_export_test.go
Labels: BACKPORT

#717 Remove GasAdjustment override from ChainSpec
  chainspec.go
  chainspec_test.go
Labels: BACKPORT

#739 Add HasCommand function for chain binaries
  chain/cosmos/chain_node.go
Labels: BACKPORT

#736 SDK 47+ unsafe-reset w/ backwards compatibility
  chain/cosmos/chain_node.go
Labels: BACKPORT

#756 Fix backport
  .github/mergify.yml
Labels: BACKPORT

#720 Docs for GitHub E2E Integration + local testing
  docs/ciTests.md
Labels: BACKPORT

#759 Remove `UsingNewGenesisCommand` config in favor of a runtime check
  chain/cosmos/chain_node.go
  chainspec.go
  chainspec_test.go
  examples/cosmos/chain_export_test.go
  examples/cosmos/sdk_boundary_test.go
  examples/ibc/interchain_accounts_test.go
  ibc/types.go
  local-interchain/cmd/local-ic/new_chain.go
  local-interchain/go.mod
  local-interchain/go.sum
  local-interchain/interchain/config.go
  local-interchain/interchain/types/chain.go
Labels: BACKPORT

#725 Add ENV variable option to keep testnet alive after test completion
  README.md
  docs/ciTests.md
  docs/envOptions.md
  internal/dockerutil/setup.go
Labels: BACKPORT

#718 Add ENV to show logs on fail, always, and never
  docs/envOptions.md
  internal/dockerutil/setup.go
Labels: BACKPORT

#747 Re-add polkadot/hyperspace support and update TestHyperspace for ibc-go wasm light client changes
  .gitignore
  chain/cosmos/08-wasm-types/client_message.go
  chain/cosmos/08-wasm-types/client_state.go
  chain/cosmos/08-wasm-types/codec.go
  chain/cosmos/08-wasm-types/consensus_state.go
  chain/cosmos/08-wasm-types/header.go
  chain/cosmos/08-wasm-types/misbehavior.go
  chain/cosmos/08-wasm-types/msgs.go
  chain/cosmos/08-wasm-types/tx.pb.go
  chain/cosmos/08-wasm-types/wasm.pb.go
  chain/cosmos/chain_node.go
  chain/cosmos/cosmos_chain.go
  chain/polkadot/keys.go
  chain/polkadot/keys_test.go
  chain/polkadot/parachain_node.go
  chain/polkadot/polkadot_chain.go
  chain/polkadot/polkadot_chain_test.go
  chain/polkadot/query.go
  chain/polkadot/relay_chain_node.go
  chain/polkadot/ss58.go
  chain/polkadot/tx.go
  chain/polkadot/wallet.go
  chainfactory.go
  chainspec.go
  examples/hyperspace/hyperspace_test.go
  examples/polkadot/ics10_grandpa_cw.wasm
  examples/polkadot/polkadot_chain_test.go
  examples/polkadot/push_wasm_client_code_test.go
  examples/polkadot/substrate_cosmos_ibc_test.go
  go.mod
  go.sum
  relayer/hyperspace/hyperspace_commander.go
  relayer/hyperspace/hyperspace_config.go
  relayer/hyperspace/hyperspace_relayer.go
  relayer/hyperspace/hyperspace_test.go
  relayer/hyperspace/wallet.go
  relayer/rly/cosmos_relayer.go
  relayerfactory.go
Labels: dont_backport

#760 Get binary build information & dependencies
  chain/cosmos/chain_node.go
  chain/cosmos/types.go
  examples/cosmos/chain_export_test.go
  examples/cosmos/chain_miscellaneous_test.go
Labels: BACKPORT

#766 Adopt the function options pattern for relayer configuration
  examples/ibc/interchain_accounts_test.go
  relayer/docker.go
  relayer/hermes/hermes_relayer.go
  relayer/hyperspace/hyperspace_relayer.go
  relayer/options.go
  relayer/rly/cosmos_relayer.go
  relayerfactory.go
Labels: BACKPORT

#790 chore: move localhost -> 127.0.0.1
  internal/dockerutil/ports.go
  internal/dockerutil/strings.go
  internal/dockerutil/strings_test.go
  local-interchain/README.md
  local-interchain/configs/server.json
  local-interchain/docs/REST_API.md
  local-interchain/docs/WINDOWS.md
  local-interchain/scripts/example_req.bash
  local-interchain/scripts/helpers/cosmwasm.py
Labels: BACKPORT

#789 add GetNode() helper
  chain/cosmos/cosmos_chain.go
Labels: BACKPORT

#710 fix: Local-interchain cleanup
  local-interchain/Makefile
  local-interchain/cmd/local-ic/chains.go
  local-interchain/cmd/local-ic/main.go
  local-interchain/cmd/local-ic/new_chain.go
  local-interchain/cmd/local-ic/root.go
  local-interchain/cmd/local-ic/start_chain.go
Labels: BACKPORT

#800 Bring back wasm encoding and example tests
  chain/cosmos/wasm/wasm.go
  examples/ibc/wasm/sample_contracts/ibc_reflect.wasm
  examples/ibc/wasm/sample_contracts/ibc_reflect_send.wasm
  examples/ibc/wasm/sample_contracts/icq.wasm
  examples/ibc/wasm/sample_contracts/reflect.wasm
  examples/ibc/wasm/wasm_ibc_test.go
  examples/ibc/wasm/wasm_icq_test.go
  go.mod
  go.sum
Labels: dont_backport
